name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # main branch'e her push yapıldığında çalışır

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v3

    - name: Deploy 🚀
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./ # Sitenizin kök dizini